"""add default_location_id to users

Revision ID: 5940900b659a
Revises: d4f00cb8970c
Create Date: 2026-09-06 00:34:52.087829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5940900b659a'
down_revision: Union[str, Sequence[str], None] = 'd4f00cb8970c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_location_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_users_default_location_id', 'users', 'locations', ['default_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_default_location_id', 'users', type_='foreignkey')
    op.drop_column('users', 'default_location_id')
    # ### end Alembic commands ###
