"""add address, phone, uniqueness and index to locations

Revision ID: d4f00cb8970c
Revises: d61f6867a357
Create Date: 2026-09-06 00:23:02.305371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f00cb8970c'
down_revision: Union[str, Sequence[str], None] = 'd61f6867a357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('address', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('phone', sa.String(), nullable=True))
    op.alter_column('locations', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_locations_org', 'locations', ['org_id'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_unique_constraint('ux_locations_org_name', 'locations', ['org_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux_locations_org_name', 'locations', type_='unique')
    op.drop_index('ix_locations_org', table_name='locations', postgresql_where=sa.text('is_active'))
    op.alter_column('locations', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('locations', 'phone')
    op.drop_column('locations', 'address')
    # ### end Alembic commands ###
